Test coverage
birs-math/proposals pull request #351
Opened 2021-08-11 07:22 UTC by devalirizwan

2021-08-11 17:47 UTC, brentkearney requested changes
Please fix issues identified by Codacy

2021-08-12 22:42 UTC, brentkearney commented on .rubocop.yml
> +  Enabled: false
Skipping the BlockLength checks in the specs is OK. Please re-enable the other tests, and refactor methods and modules that are too long, etc..

2021-08-12 22:44 UTC, brentkearney commented on app/controllers/locations_controller.rb
> +  # rubocop:enable Metrics/MethodLength
Please remove these # rubocop comments. I will skip it in Codacy if it fails.

2021-08-12 22:45 UTC, brentkearney commented on app/controllers/proposal_fields_controller.rb
> +  # rubocop:enable Metrics/MethodLength
Please remove the skip

2021-08-12 22:45 UTC, brentkearney commented
Please remove all  # rubocop:enable Metrics/MethodLength

2021-09-03 07:18 UTC, devhassanmahmood commented
Hey - @brentkearney Can you please look why tests are running for subjects_controller.rb ? I have removed subjects_controller file and also removed from spec/requests folder. Why it is considering it?

2021-11-04 18:18 UTC, closed without merging