Added cover letter field and new email types
birs-math/proposals pull request #664
Opened 2021-11-03 13:39 UTC by devalirizwan

2021-11-03 14:50 UTC, devhassanmahmood commented
![](https://github.trello.services/images/mini-trello-icon.png) [A new field "Cover letter explaining changes" is added to the proposal application Step 1 when the Revision - Round 2 is requested by the staff member](https://trello.com/c/fsI7OxVT/661-a-new-field-cover-letter-is-added-when-the-revision-is-requested-by-the-staff-member)

2021-11-03 18:02 UTC, brentkearney requested changes
Please refactor to change static "revision_1", "revision_2", etc, to dynamic revision numbers. Assume there could be any number of revisions. 

Also: please avoid using @instance variables unless they are absolutely necessary. Pass arguments to methods.

2021-11-03 18:02 UTC, brentkearney commented on app/views/proposals/_proposal.html.erb
> +                            <%= f.text_area(:cover_letter, size: '5x5', class:'form-control', value: @proposal&.cover_letter, disabled: action)%>
`, disabled: action) %>`

2021-11-03 18:11 UTC, brentkearney commented on app/views/proposals/_proposal.html.erb
> +                            <%= f.text_area(:cover_letter, size: '5x5', class:'form-control', value: @proposal&.cover_letter, disabled: action)%>
(missing space)

2021-11-03 18:15 UTC, brentkearney commented
Also, refactoring methods to reduce size & complexity would be helpful, if there is time.

https://app.codacy.com/gh/birs-math/proposals/pullRequest?prid=8354348

2021-11-04 15:09 UTC, devhassanmahmood commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a new status 'Shortlisted' to the proposal workflow](https://trello.com/c/J75jUgv5/663-add-a-new-status-shortlisted-to-the-proposal-workflow)

2021-11-04 18:16 UTC, merged