Added runs and cases tables
birs-math/proposals pull request #698
Opened 2021-11-23 14:46 UTC by devalirizwan

2021-11-23 14:47 UTC, devalirizwan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add database tables: schedule_runs (Runs) and schedules (Cases)](https://trello.com/c/QV6EjsI3/688-add-database-tables-scheduleruns-runs-and-schedules-cases)

2021-11-24 17:56 UTC, brentkearney commented
Can you please change `Runs` to `ScheduleRuns` / `schedule_runs`?

2021-11-24 17:57 UTC, brentkearney requested changes
Please rename the `:runs` table to `:schedule_runs`.

2021-11-24 17:58 UTC, brentkearney commented on db/migrate/20211123072903_create_runs.rb
> +      t.string :location
Perhaps this should be `t.integer :location_id` ?

2021-11-29 16:59 UTC, brentkearney approved these changes

2021-11-29 16:59 UTC, merged