Added fields in show/edit page
birs-math/proposals pull request #709
Opened 2021-11-25 14:42 UTC by devalirizwan

2021-11-25 14:57 UTC, devalirizwan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add new fields to Proposals](https://trello.com/c/BLvZ0XR9/690-add-new-fields-to-proposals)

2021-11-25 14:59 UTC, devalirizwan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update the Proposals Show/Edit views to include the new proposal fields (assigned_location, same_week_as, etc)](https://trello.com/c/xqIoYDA6/708-update-the-proposals-show-edit-views-to-include-the-new-proposal-fields-assignedlocation-sameweekas-etc)

2021-11-25 15:00 UTC, devalirizwan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add column for "Location", to show  the `proposal.assigned_location` in the list of proposals.](https://trello.com/c/h47Sjcbx/707-add-column-for-location-to-show-the-proposalassignedlocation-in-the-list-of-proposals)

2021-11-25 21:23 UTC, brentkearney requested changes

2021-11-25 21:23 UTC, brentkearney commented on app/views/proposals/_proposal.html.erb
> +                          <label for="same_week">(Links to another proposal that is to be scheduled the same week as this proposal.)</label>
Shouldn't it be `same_week_as` ?

2021-11-25 21:23 UTC, brentkearney commented on app/controllers/submit_proposals_controller.rb
> +                  :no_latex, :preamble, :bibliography, :cover_letter, :same_week_as)
What about `:week_after` and `:assigned_date`?

2021-11-25 21:23 UTC, brentkearney commented on app/views/submitted_proposals/_form.html.erb
> +                          <label for="same_week">(Links to another proposal that is to be scheduled the same week as this proposal.)</label>
`:same_week_as`?

2021-11-29 17:28 UTC, brentkearney requested changes

2021-11-29 17:28 UTC, brentkearney commented on app/views/proposals/_proposal.html.erb
>                          <div class="mb-3">
The same_week_as and week_after fields are missing - should be a list of proposal codes of the proposals that were accepted by the peer review process for the given year. Status: decision approved ? (ask PM)

2021-11-30 18:49 UTC, brentkearney requested changes
Please make the assigned_date field a select menu of available dates, based on the `Location.start_date` and `Location.end_date`, minus `Location.exclude_dates`.

2021-11-30 18:49 UTC, brentkearney commented on app/views/submitted_proposals/_form.html.erb
> +                          <%= f.text_field :assigned_date, class: 'form-control w-25', disabled: true, value:@proposal.assigned_date %>
`assigned_date` should be a `Date` object

2021-11-30 18:49 UTC, brentkearney commented on app/views/proposals/_proposal.html.erb
> +                        </div>
I'm not sure a text field will work for a `Date` object. Perhaps a select menu showing available dates between `Location.start_date` and `Location.end_date`, displayed as `start_date.strftime("%Y-%m-%d")`.

2021-12-01 17:54 UTC, brentkearney requested changes

2021-12-01 17:54 UTC, brentkearney commented on app/helpers/proposals_helper.rb
> +    Proposal.all.where(outcome: "approved").map { |pro| [pro.code] }
I believe the Outcome should be "Approved"...

2021-12-01 17:54 UTC, brentkearney commented on app/helpers/proposals_helper.rb
> +    return "" unless location
In Ruby if `location` is set to "", this would still return true. Should be more explicit, like `return "" unless location.present?`

2021-12-01 17:54 UTC, brentkearney commented on app/helpers/proposals_helper.rb
> +    get_assigne_dates(start_date, end_date, location)
"assign" has no "e" on the end

Also excluding dates is the opposite of assigning them, so this naming is confusing. A better method name would be `get_excluded_dates`.

2021-12-01 20:45 UTC, merged